//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF4_5Session.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbStrazhnikEntities : DbContext
    {
        public dbStrazhnikEntities()
            : base("name=dbStrazhnikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DataAddPermission> DataAddPermission { get; set; }
        public virtual DbSet<DataViewPermission> DataViewPermission { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<ReportPermission> ReportPermission { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserLogin> UserLogin { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
        public virtual DbSet<Verify> Verify { get; set; }
    }
}
