//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF4_5Session.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportPermission
    {
        public int ID { get; set; }
        public string Title { get; set; }
    }
}
