//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF4_5Session.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string FisrtName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public Nullable<int> IDGender { get; set; }
        public string Post { get; set; }
        public Nullable<int> IDUserType { get; set; }
        public string SecretWord { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Image { get; set; }
        public Nullable<int> IDDataAddPermission { get; set; }
        public Nullable<int> IDReportPermission { get; set; }
        public Nullable<int> IDDataViewPermission { get; set; }
        public Nullable<int> IDVerify { get; set; }
    
        public virtual DataAddPermission DataAddPermission { get; set; }
        public virtual DataViewPermission DataViewPermission { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ReportPermission ReportPermission { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual Verify Verify { get; set; }
    }
}
